### ISSUE TITLE
faq js - is it possible to get the individual paragraphs in one function?

### ISSUE THREAD

**Issue by seichris** [trustlines-network/trustlines-network.github.io#15]
faq-content.html used to link to general.md
right now all the faq text is added to faq-content.html for the paragraphs to be able to collapse

is it possible to link faq-content.html used to link to general.md again?

pseudo code:
{{ faq.content }} -> {{ faq.content }} + 1

**Comment by Kispus** [comment]
Works - Seichris will ask Ulo if there is any remaining optimisation possibilities
