### ISSUE TITLE
Headbar issue, navigation bar is no longer transparent and text should be smaller

### ISSUE THREAD

**Issue by KristofferTrustlines** [trustlines-network/trustlines-network.github.io#9]
Bernd:
![image](https://cloud.githubusercontent.com/assets/23054923/22150948/29bad008-df1c-11e6-991e-56b89b162c9d.png)
comparison of bar to facebook
and I would make a smaller font size for the head bar
maybe it is just on my set up but it is really big

I am not sure how it looks on other set ups
I guess it depends on the screen resolution and so on
it is just way bigger than it is usually

**Comment by seichris** [comment]
^that's what she said
